### ISSUE TITLE
How to use this with neovim?

### ISSUE THREAD

**Issue by mr-nice** [vala-lang/tree-sitter-vala#4]
Hi all,
I know this is not the support channel for neovim but as most people using tree sitter have a strong relationship to neovim, please  help me out :)

First of all thanks for all that awesome vala stuff. I currently try to install this tree sitter plugin within neovim. I already got the awesome vala_ls working but I have no syntax highlighting. Therefore I tried to install this with TSInstall vala which pulls from this repository.

I installed it manually within Arch as suggested in the readme and can parse basic vala files with the tree-sitter cli. But I have no clue how to integrate it within neovim.

Can you help me out to glue the missing parts? I'm willing to do a pull request with all the information to the README.md.

Thanks in advance,
mr-nice

**Comment by Prince781** [comment]
Sure. You already installed the NVIM tree-sitter plugin and installed this grammar with `:TSInstall vala`. You also need to install [`vala.vim`](https://github.com/vala-lang/vala.vim) so that the filetype gets recognized. Then you should be good to go.

If you use a plugin manager like Vim Plug, add this to your config:
```vim
Plug 'vala-lang/vala.vim'
```

Then install with `:PlugUpdate`. If you use a different plugin manager the steps will be different.

**Comment by mr-nice** [comment]
Thanks, for the help :) It works
